version: '3.8'

services:
  ner-leaderboard:
    image: ner-leaderboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"

    volumes:
      - ${PWD}/DATA/testsets:/mounted/testsets
      - ${PWD}/DATA/submissions.db:/mounted/submissions.db
      - ${PWD}/DATA/users_config.yaml:/mounted/users_config.yaml
      - ${PWD}/DATA/saved_submissions:/mounted/saved_submissions

    environment:
      TESTSETS_PATH: /mounted/testsets
      DB_PATH: /mounted/submissions.db
      USER_CONFIG_PATH: /mounted/users_config.yaml
      SUBMISSION_SAVE_PATH: /mounted/saved_submissions

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8501"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

    labels:
      maintainer: "wesam.alnabki@gmail.com"
      service: "NER Leaderboard"
